-- Add separate address fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS cep VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS street VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS number VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS complement VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS neighborhood VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS state VARCHAR(50);
